export enum MsgMarksEnum {
  TEST_SEND_CLIENT = 'test-send',
  TEST_RECV_CLIENT = 'test-recv',
  TEST_RECV = 'test-marks-recv',
  TEST_SEND = 'test-marks-send',
  MAP_INIT_SEND_CLIENT = 'map-init-send',
  MAP_INIT_RECV_CLIENT = 'map-init-recv',
  MAP_INIT_RECV = 'map-init-marks-recv',
  MAP_INIT_SEND = 'map-init-marks-send',
  MARK_GET_SEND = 'mark-get-send',
  MARK_GET_RECV = 'mark-get-recv',
  MARK_VERIFY_TRUE_SEND = 'mark-verify-true-send',
  MARK_VERIFY_TRUE_RECV = 'mark-verify-true-recv',
  MARK_VERIFY_FALSE_SEND = 'mark-verify-false-send',
  MARK_VERIFY_FALSE_RECV = 'mark-verify-false-recv',
  GET_VERIFY_SEND = 'get-verify-send',
  GET_VERIFY_RECV = 'get-verify-recv',
  CATEGORIES_SEND = 'categories-send',
  CATEGORIES_RECV = 'categories-recv',
  CREATE_MARK_SEND = 'create-mark-send',
  CREATE_MARK_RECV = 'create-mark-recv',
}
