export enum MsgMarksEnum {
  MAP_INIT_CLIENT = 'map-init-send',
  MAP_INIT = 'map-init-marks-send',
  MARK_GET = 'mark-get-send',
  MARK_VERIFY_TRUE = 'mark-verify-true-send',
  MARK_VERIFY_FALSE = 'mark-verify-false-send',
  GET_VERIFY = 'get-verify-send',
  CATEGORIES = 'categories-send',
  CREATE_MARK = 'create-mark-send',
  CATEGORIES_STATS = 'categories-stats-send',
  CREATE_CATEGORY = 'create-category-send',
  UPDATE_CATEGORY = 'update-category-send',
  DELETE_CATEGORY = 'delete-category-send',
  GET_CATEGORY = 'get-category-send',
}
